/*
 * Auto Complete [VERSION]
 * [DATE]
 * Corey Hart @ http://www.codenothing.com
 */
(function(h,U,i){function N(f,s){if(N.flag!==g){N.flag=g;X.bind("click.autoComplete",function(x){h(j.getFocus()).trigger("autoComplete.document-click",[x])})}f=f.closest("form");var m=f.data("ac-inputs")||[],z;m[s]=g;f.data("ac-inputs",m);f.data("autoComplete")!==g&&f.bind("submit.autoComplete",function(x){return(z=h(j.getFocus())).length?z.triggerHandler("autoComplete.form-submit",[x]):g})}function ca(f,s){if(N.flag===g&&j.length===0){N.flag=q;X.unbind("click.autoComplete")}f=f.closest("form");var m=
f.data("ac-inputs"),z=-1,x=(m||[]).length;for(m[s]=q;++z<x;)if(m[z]===g)return;f.unbind("submit.autoComplete")}function Y(f,s){if(!h.isArray(s.supply))return[];f=-1;for(var m=s.supply.length,z=[],x;++f<m;){x=(x=s.supply[f])&&x.value?x:{value:x};z.push(x)}return z}h.fn.autoComplete=function(){var f=Z.call(arguments),s=this,m=f.shift(),z=typeof m==="string";if(z)m=m.replace(".","-");f=m==="button-supply"||m==="direct-supply"?h.isArray(f[0])&&h.isArray(f[0][0])?f[0]:f:f[1]===i&&h.isArray(f[0])?f[0]:
f;return z?s[m==="option"&&f.length<2?"triggerHandler":"trigger"]("autoComplete."+m,f):m&&m[h.expando]?s.trigger(m,f):s.each(function(){da(this,m)})};h.fn.bgiframe=h.fn.bgiframe?h.fn.bgiframe:h.fn.bgIframe?h.fn.bgIframe:function(){return this};var g=true,q=false,Z=Array.prototype.slice,X=h(U.document),y="autoComplete_"+h.expando,G={backspace:8,tab:9,enter:13,space:32,pageup:33,pagedown:34,up:38,down:40},j=h.autoComplete={version:"[VERSION]",counter:0,length:0,stack:{},order:[],hasFocus:q,getFocus:function(){return j.order[0]?
j.stack[j.order[0]]:i},getPrevious:function(){for(var f=0,s=j.order.length;++f<s;)if(j.order[f])return j.stack[j.order[f]];return i},remove:function(f){for(var s=-1,m=j.order.length;++s<m;)if(j.order[s]===f)j.order[s]=i;j.stack[f]=i;j.length--;delete j.stack[f]},getAll:function(){for(var f=-1,s=j.counter,m=[];++f<s;)j.stack[f]&&m.push(j.stack[f]);return h(m)},defaults:{backwardsCompatible:q,ajax:"ajax.php",ajaxCache:h.ajaxSettings.cache,dataSupply:[],dataFn:i,formatSupply:i,list:"auto-complete-list",
rollover:"auto-complete-list-rollover",width:i,striped:i,maxHeight:i,newList:q,postVar:"value",postData:{},postFormat:i,minChars:1,maxItems:-1,maxRequests:0,requestType:"POST",inputControl:i,autoFill:q,nonInput:i,multiple:q,multipleSeparator:" ",onBlur:i,onFocus:i,onHide:i,onLoad:i,onMaxRequest:i,onRollover:i,onSelect:i,onShow:i,onSubmit:function(){return g},spinner:i,onListFormat:i,preventEnterSubmit:g,delay:0,useCache:g,cacheLimit:50}},da=function(f,s){function m(b,a,c,k,A){a.spinner&&a.spinner.call(f,
b,{active:g,settings:a,cache:c,ul:e});if(J)J=clearTimeout(J);if(a.delay>0&&A===i)return J=U.setTimeout(function(){m(b,a,c,k,g);J=clearTimeout(J)},a.delay);R&&R.abort();if(a.useCache&&c.list[c.val])return S(b,c.list[c.val],a,c,k);if(a.dataSupply.length)return z(b,a,c,k);if(a.maxRequests&&++V>=a.maxRequests){e.html("").hide(b);a.spinner&&a.spinner.call(f,b,{active:q,settings:a,cache:c,ul:e});if(a.onMaxRequest&&V===a.maxRequests)return a.onMaxRequest.apply(f,a.backwardsCompatible?[c.val,e,b,u,a,c]:[b,
{search:c.val,val:u,settings:a,cache:c,ul:e}]);return q}a.postData[a.postVar]=c.val;return R=h.ajax({type:a.requestType,url:a.ajax,cache:a.ajaxCache,dataType:"json",data:a.postFormat?a.postFormat.call(f,b,{data:a.postData,search:c.val,val:u,settings:a,cache:c,ul:e}):a.postData,success:function(D){S(b,D,a,c,k)},error:function(){e.html("").hide(b);a.spinner&&a.spinner.call(f,b,{active:q,settings:a,cache:c,ul:e})}})}function z(b,a,c,k){var A=[],D=[],O=h.isFunction(a.dataFn),K=O?i:new RegExp("^"+c.val,
"i"),P=0,B,E=-1,ea=a.dataSupply.length;if(a.formatSupply)A=a.formatSupply.call(f,b,{search:c.val,supply:a.dataSupply,settings:a,cache:c,ul:e});else for(;++E<ea;){B=a.dataSupply[E];B=typeof B==="object"&&B.value?B:{value:B};D=a.backwardsCompatible?[c.val,B.value,A,E,a.dataSupply,e,b,a,c]:[b,{search:c.val,entry:B.value,list:A,i:E,supply:a.dataSupply,settings:a,cache:c,ul:e}];if(O&&a.dataFn.apply(f,D)||!O&&B.value.match(K)){if(a.maxItems>-1&&++P>a.maxItems)break;A.push(B)}}return S(b,A,a,c,k)}function x(b){if(H){if(d.onSelect)d.onSelect.apply(f,
d.backwardsCompatible?[t,o,e,b,d,l]:[b,{data:t,li:o,settings:d,cache:l,ul:e}]);Q();u=p.val();if(n.type==="keydown")n["enter_"+y]=g}return e.hide(b)}function $(b){o&&o.removeClass(d.rollover);e.show(b);o=F.eq(r).addClass(d.rollover);t=C[r];if(!o.length||!t)return q;Q(t.value);if(d.onRollover)d.onRollover.apply(f,d.backwardsCompatible?[t,o,e,b,d,l]:[b,{data:t,li:o,settings:d,cache:l,ul:e}]);b=r*L;if(b<M-T){M=b+T;e.scrollTop(b)}return o}function aa(b){o&&o.removeClass(d.rollover);e.show(b);o=F.eq(r).addClass(d.rollover);
t=C[r];if(!o.length||!t)return q;Q(t.value);var a=(r+1)*L;if(a>M)e.scrollTop((M=a)-T);if(d.onRollover)d.onRollover.apply(f,d.backwardsCompatible?[t,o,e,b,d,l]:[b,{data:t,li:o,settings:d,cache:l,ul:e}]);return o}function ba(){var b=e.hide,a=e.show,c=e.data("ac-inputs")||{};if(!e[y]){e.hide=function(k,A,D){d.onHide&&H&&d.onHide.call(f,k,{ul:e,settings:d,cache:l});H=q;return b.call(e,A,D)};e.show=function(k,A,D){d.onShow&&!H&&d.onShow.call(f,k,{ul:e,settings:d,cache:l});H=g;return a.call(e,A,D)};e[y]=
g}c[v]=g;return e.data("ac-inputs",c)}function Q(b){var a,c,k;if(b===i||b==="")a=c=p.val().length;else{if(I)b=u.substr(0,u.length-u.split(I).pop().length)+b+I;a=u.length;c=b.length;p.val(b)}if(!d.autoFill||a>c)return q;else if(f.createTextRange){k=f.createTextRange();if(b===i)k.move("character",a);else{k.collapse(g);k.moveStart("character",a);k.moveEnd("character",c)}k.select()}else if(f.setSelectionRange)f.setSelectionRange(a,c);else if(f.selectionStart){f.selectionStart=a;f.selectionEnd=c}return g}
function S(b,a,c,k,A){C=c.onLoad?c.onLoad.call(f,b,{list:a,settings:c,cache:k,ul:e}):a;c.spinner&&c.spinner.call(f,b,{active:q,settings:c,cache:k,ul:e});if(c.useCache&&k.list[k.val]===i){k.length++;k.list[k.val]=a;if(k.length>c.cacheLimit){k.list={};k.length=0}}if(!C||C.length<1)return e.html("").hide(b);r=-1;a=p.offset();var D=[],O=0,K=-1,P=q,B=C.length;if(c.onListFormat)c.onListFormat.call(f,b,{list:C,settings:c,cache:k,ul:e});else{for(;++K<B;)if(C[K].value){if(c.maxItems>-1&&++O>c.maxItems)break;
D.push(c.striped&&P?'<li class="'+c.striped+'">':"<li>",C[K].display||C[K].value,"</li>");P=!P}e.html(D.join(""))}F=e.children("li");if(c.autoFill&&!A){r=0;t=C[0];Q(t.value);o=F.eq(0).addClass(c.rollover)}e.unbind(".autoComplete").data("ac-input-index",v).delegate("li","mouseleave.autoComplete",function(){o&&o.removeClass(c.rollover)}).delegate("li","mouseenter.autoComplete",function(E){o=h(this).addClass(c.rollover);r=F.index(o[0]);t=C[r];if(c.onRollover)c.onRollover.apply(f,c.backwardsCompatible?
[t,o,e,E,c,k]:[E,{data:t,li:o,settings:c,cache:k,ul:e}])}).bind("click.autoComplete",function(E){p.trigger("focus",[y]);p.val(u===I?u.substr(0,u.length-u.split(I).pop().length)+t.value+I:t.value);e.hide(E);Q();if(c.onSelect)c.onSelect.apply(f,c.backwardsCompatible?[t,o,e,E,c,k]:[E,{data:t,li:o,settings:c,cache:k,ul:e}])}).css({top:a.top+p.outerHeight(),left:a.left,width:c.width}).scrollTop(0);L=F.eq(0).outerHeight();if(c.maxHeight)e.css({height:L*F.length>c.maxHeight?c.maxHeight:"auto",overflow:"auto"});
console.warn(e.data("events"));M=T=e.outerHeight();W=L===0?0:Math.floor(M/L);n.timeStamp=(new Date).getTime();return e.show(b)}j.length++;j.counter++;var p=h(f).attr("autocomplete","off"),w=g,n={},u="",C=[],F={length:0},o,M,T,L,W,H=q,J,R,r=-1,t,I,v=j.counter,V=0,l={length:0,val:i,list:{}},d=h.extend({width:p.outerWidth()},j.defaults,s||{},h.metadata?p.metadata():{}),e=!d.newList&&h("ul."+d.list)[0]?h("ul."+d.list).eq(0).bgiframe().data("autoComplete",g):h("<ul/>").appendTo("body").addClass(d.list).bgiframe().hide().data({"ac-selfmade":g,
autoComplete:g});p.data({autoComplete:g,"ac-input-index":v,"ac-active":w,"ac-initial-settings":h.extend(g,{},d),"ac-settings":d}).bind(U.opera?"keypress.autoComplete":"keydown.autoComplete",function(b){if(!w)return g;var a=(n=b).keyCode,c=q;if(a===G.tab&&H)x(b);else if(a===G.enter&&o){c=d.preventEnterSubmit&&H?q:g;x(b)}else if(a===G.up)if(r>0){r--;$(b)}else{r=-1;p.val(u);e.hide(b)}else if(a===G.down){if(r<F.length-1){r++;aa(b)}}else if(a===G.pageup){if(r>0){r-=W;if(r<0)r=0;$(b)}}else if(a===G.pagedown){if(r<
F.length-1){r+=W;if(r>F.length-1)r=F.length-1;aa(b)}}else if(d.nonInput&&h.inArray(a,d.nonInput))e.html("").hide(b);else return g;n["keydown_"+y]=g;return c}).bind({"keyup.autoComplete":function(b){if(!w||n["keydown_"+y])return g;u=p.val();var a=(n=b).keyCode,c=I?u.split(I).pop():u;if(a!=G.enter){l.val=d.inputControl===i?c:d.inputControl.apply(f,d.backwardsCompatible?[c,a,e,b,d,l]:[b,{val:c,key:a,settings:d,cache:l,ul:e}]);if(l.val.length>=d.minChars)m(b,d,l,a===G.backspace||a===G.space);else a==
G.backspace&&e.html("").hide(b)}},"blur.autoComplete":function(b){if(!w||H)return g;n=b;p.data("ac-hasFocus",q);r=-1;j.order[0]!==i&&j.order.unshift(i);j.hasFocus=q;e.hide(b);if(d.onBlur)d.onBlur.apply(f,d.backwardsCompatible?[u,e,b,d,l]:[b,{val:u,settings:d,cache:l,ul:e}])},"focus.autoComplete":function(b,a){if(!w||j.focus===v&&a===y||n["enter_"+y])return g;n=b;v!==e.data("ac-input-index")&&e.html("").hide(b);if(j.order[0]===i)if(j.order[1]===v)j.order.shift();else j.order[0]=v;else j.order[0]!=
v&&j.order[1]!=v&&j.order.unshift(v);j.order.length>j.defaults.cacheLimit&&j.order.pop();j.hasFocus=g;p.data("ac-hasFocus",g);if(d.onFocus)d.onFocus.apply(f,d.backwardsCompatible?[e,b,d,l]:[b,{settings:d,cache:l,ul:e}])},"autoComplete.document-click":function(b,a){if(w&&H&&(!n||a.timeStamp-n.timeStamp>200)&&h(a.target).closest("ul").data("ac-input-index")!==v){e.hide(a);n=a;p.blur()}},"autoComplete.form-submit":function(b,a){if(!w)return g;n=a;return d.preventEnterSubmit&&(H||n["enter_"+y])?q:d.onSubmit.call(f,
a,{form:this,settings:d,cache:l,ul:e})},"autoComplete.settings":function(b,a){if(!w)return g;var c;if(h.isFunction(a)){a=a.apply(f,d.backwardsCompatible?[d,l,e,b]:[b,{settings:d,cache:l,ul:e}]);if(h.isArray(a)&&a[0]!==i){d=h.extend(g,{},d,a[0]||d);l=h.extend(g,{},l,a[1]||l)}}else d=h.extend(g,{},d,a||{});e=!d.newList&&e.hasClass(d.list)?e:!d.newList&&(c=h("ul."+d.list).eq(0)).length?c.bgiframe().data("autoComplete",g):h("<ul/>").appendTo("body").addClass(d.list).bgiframe().hide().data({"ac-selfmade":g,
autoComplete:g});ba();d.requestType=d.requestType.toUpperCase();I=d.multiple?d.multipleSeparator:i;p.data("ac-settings",d);return n=b},"autoComplete.flush":function(b,a){if(!w)return g;a||(V=0);l={length:0,val:i,list:{}};return n=b},"autoComplete.button-ajax":function(b,a,c){if(!w)return g;if(typeof a==="string"){c=a;a={}}n=b;p.trigger("focus",[y]);l.val=c||"button-ajax_"+y;return m(b,h.extend(g,{},d,{maxItems:-1,postData:a||{}}),l)},"autoComplete.button-supply":function(b,a,c){if(!w)return g;if(typeof a===
"string"){c=a;a=i}n=b;p.trigger("focus",[y]);l.val=c||"button-supply_"+y;a=h.isArray(a)&&a.length?a:d.dataSupply;return m(b,h.extend(g,{},d,{maxItems:-1,dataSupply:a,formatSuppy:Y}),l)},"autoComplete.direct-supply":function(b,a,c){if(!w)return g;if(typeof a==="string"){c=a;a=i}n=b;p.trigger("focus",[y]);l.val=c||"direct-supply_"+y;a=h.isArray(a)&&a.length?a:d.dataSupply;return S(b,a,h.extend(g,{},d,{maxItems:-1,dataSupply:a,formatSuppy:Y}),l)},"autoComplete.search":function(b,a){if(!w)return g;l.val=
a||"";return m(n=b,d,l)},"autoComplete.option":function(b){if(!w)return g;var a=Z.call(arguments),c=a.length;n=b;if(c===3){d[a[1]]=a[2];return a[2]}else if(c===2)switch(a[1]){case "ul":return e;case "cache":return l;case "xhr":return R;case "input":return p;default:return d[a[1]]||i}else return d},"autoComplete.enable":function(b){p.data("ac-active",w=g);return n=b},"autoComplete.disable":function(b){p.data("ac-active",w=q);e.html("").hide(b);return n=b},"autoComplete.destroy":function(b){var a=e.html("").hide(b).data("ac-inputs"),
c;p.removeData("autoComplete").removeData("ac-input-index").removeData("ac-initial-settings").removeData("ac-settings").removeData("ac-active").unbind(".autoComplete autoComplete").closest("form").unbind("submit.autoComplete-"+v);j.remove(v);ca(p,v);w=q;a[v]=i;n=b;for(c in a)if(a.hasOwnProperty(c)&&a[c]===g)return n;e.data("ac-input-index")===v&&e.removeData("ac-input-index");e.data("ac-selfmade")===g&&e.remove();return n}});ba();d.requestType=d.requestType.toUpperCase();I=d.multiple?d.multipleSeparator:
i;j.stack[v]=f;N(p,v)}})(jQuery,window||this);
